#       _                 _     _       
#   ___| |_ __ _ _ __ ___| |__ (_)_ __  
#  / __| __/ _` | '__/ __| '_ \| | '_ \ 
#  \__ \ || (_| | |  \__ \ | | | | |_) |
#  |___/\__\__,_|_|  |___/_| |_|_| .__/ 
#                                |_|    
#  by Fráter Iván ©(2024)

# Set prompt format
format = """$os$username$hostname$directory$git_branch$git_status"""
right_format = """$cmd_duration$time$battery"""

# Show OS symbol
[os]
format = '[$symbol](bold white) '
disabled = false

[os.symbols]
Linux = " "
Macos = " "

# Show username
[username]
style_user = 'white bold'
style_root = 'red bold'
format = '[$user]($style) '
disabled = false
show_always = true

# Show hostname
[hostname]
ssh_only = false
format = 'on [$hostname](bold white) '
disabled = false

# Show current directory
[directory]
truncation_length = 5
truncation_symbol = '…/'
home_symbol = '󰋜 ~'
read_only_style = 'red'
read_only = '  '
format = 'at [$path]($style)[$read_only]($read_only_style) '

# Show current git branch
[git_branch]
symbol = ' '
format = 'via [$symbol$branch]($style)'
# truncation_length = 4
truncation_symbol = '…/'
style = 'bold green'

# Show current git status
[git_status]
format = '([ \( $all_status$ahead_behind\)]($style) )'
style = 'bold green'
conflicted = '[ confliced=${count}](red) '
up_to_date = '[󰘽 up-to-date](green) '
untracked = '[󰋗 untracked=${count}](red) '
ahead = ' ahead=${count}'
diverged = ' ahead=${ahead_count}  behind=${behind_count}'
behind = ' behind=${count}'
stashed = '[ stashed=${count}](green) '
modified = '[󰛿 modified=${count}](yellow) '
staged = '[󰐗 staged=${count}](green) '
renamed = '[󱍸 renamed=${count}](yellow) '
deleted = '[󰍶 deleted=${count}](red) '

# Show command duration
[cmd_duration]
disabled = false
show_milliseconds = true
min_time = 1
format = 'took [$duration](bold white) '

# Show time
[time]
disabled = false
format = '[at $time ](bold white)'
time_format = '%T'

# Show battery info
[battery]
full_symbol = '󰁹'
charging_symbol = '󰂄'
discharging_symbol = '󰂃'
format = '| [$symbol $percentage]($style)'

[[battery.display]]
threshold = 100
style = 'bold green'

[[battery.display]]
threshold = 30
style = 'bold yellow'

[[battery.display]]
threshold = 20
style = 'bold red'

[[battery.display]]
threshold = 10
style = 'bold green'